# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Junho Park
email: junho@junhopark.com
description: >- # this means to ignore newlines until "baseurl:"
  My thoughts on software, being a people manager, music, life, and God
twitter_username:
github_username:
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:year/:month/:day/:title.html
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-1362086-1"
    anonymize_ip: false # default

author:
  name   : "Junho Park"
  avatar : "/assets/images/headshot-junho-park-2018.jpg"
  bio    : "My thoughts on software, managing people, music, God, and life"
  links:
    # - label: "Website"
      # icon: "fas fa-fw fa-link"
      # url: "https://www.junhopark.com"
    # - label: "Twitter"
      # icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    # - label: "GitHub"
      # icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    # - label: "Instagram"
      # icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "http://linkedin.com/in/junhopark"

footer:
  links:
    # - label: "Twitter"
      # icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    # - label: "GitHub"
      # icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    # - label: "Instagram"
      # icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"
    # - label: "LinkedIn"
      # icon: "fab fa-fw fa-linkedin"
      # url: "http://linkedin.com/in/junhopark"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
 type: liquid
 path: /categories/
tag_archive:
  type: liquid
  path: /tags/
